''------------------------------------------------------------------------------
'' <auto-generated>
''    Este código se generó a partir de una plantilla.
''
''    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
''    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
'' </auto-generated>
''------------------------------------------------------------------------------

'Imports System
'Imports System.Collections.Generic
'Imports SigeCom.DTO.Base
'Imports System.Runtime.Serialization


'<DataContract()>
'    Partial Public Class ContratoTarifaDTO
'        Inherits Base.BaseDTO
'        Implements IEquatable(Of ContratoTarifaDTO)

'        Public Sub New()
'            _IdContratoTarifa = 0   ' Long
'            _Entorno = String.Empty ' String
'            _CodigoContrato = Nothing   ' Nullable(Of Long)
'            _IdTarifa = Nothing ' Nullable(Of Long)
'            _IdTarifaGrupo = Nothing    ' Nullable(Of Long)
'            _IdPerfilFacturacion = Nothing  ' Nullable(Of Long)
'            _FechaDesde = Nothing   ' Nullable(Of Date)
'            _FechaHasta = Nothing   ' Nullable(Of Date)
'            _Aviso = Nothing    ' Nullable(Of Boolean)
'            _IdContratoTarifaOld = Nothing  ' Nullable(Of Long)
'            _IsAjusteCAPGas = Nothing   ' Nullable(Of Boolean)
'        End Sub

'        Public Overrides Function Difference(other As BaseGenericDTO) As DifferenceDTO
'            If other Is Nothing Then Throw New ArgumentException("other is null")
'            If Not TypeOf other Is ContratoTarifaDTO Then Throw New ArgumentException("Type of other invalid")
'            Dim otherDTO As ContratoTarifaDTO = CType(other, ContratoTarifaDTO)
'            Dim dif As New List(Of String)

'            If Not IsEqual(Me.IdContratoTarifa, otherDTO.IdContratoTarifa) Then dif.Add("IdContratoTarifa")
'            If Not IsEqual(Me.Entorno, otherDTO.Entorno) Then dif.Add("Entorno")
'            If Not IsEqual(Me.CodigoContrato, otherDTO.CodigoContrato) Then dif.Add("CodigoContrato")
'            If Not IsEqual(Me.IdTarifa, otherDTO.IdTarifa) Then dif.Add("IdTarifa")
'            If Not IsEqual(Me.IdTarifaGrupo, otherDTO.IdTarifaGrupo) Then dif.Add("IdTarifaGrupo")
'            If Not IsEqual(Me.IdPerfilFacturacion, otherDTO.IdPerfilFacturacion) Then dif.Add("IdPerfilFacturacion")
'            If Not IsEqual(Me.FechaDesde, otherDTO.FechaDesde) Then dif.Add("FechaDesde")
'            If Not IsEqual(Me.FechaHasta, otherDTO.FechaHasta) Then dif.Add("FechaHasta")
'            If Not IsEqual(Me.Aviso, otherDTO.Aviso) Then dif.Add("Aviso")
'            If Not IsEqual(Me.IdContratoTarifaOld, otherDTO.IdContratoTarifaOld) Then dif.Add("IdContratoTarifaOld")
'            If Not IsEqual(Me.IsAjusteCAPGas, otherDTO.IsAjusteCAPGas) Then dif.Add("IsAjusteCAPGas")
'            Return New DifferenceDTO(Me.GetType.ToString, Me.IDEntityDTO, dif)
'        End Function

'        Public Overridable Function GetClone() As ContratoTarifaDTO
'            Dim clone As New ContratoTarifaDTO
'            clone.IdContratoTarifa = _IdContratoTarifa
'            clone.Entorno = _Entorno
'            clone.CodigoContrato = _CodigoContrato
'            clone.IdTarifa = _IdTarifa
'            clone.IdTarifaGrupo = _IdTarifaGrupo
'            clone.IdPerfilFacturacion = _IdPerfilFacturacion
'            clone.FechaDesde = _FechaDesde
'            clone.FechaHasta = _FechaHasta
'            clone.Aviso = _Aviso
'            clone.IdContratoTarifaOld = _IdContratoTarifaOld
'            clone.IsAjusteCAPGas = _IsAjusteCAPGas
'            Return clone
'        End Function

'        Public Overloads Function Equals(other As ContratoTarifaDTO) As Boolean _
'         Implements IEquatable(Of ContratoTarifaDTO).Equals
'            If other Is Nothing Then Return False
'            If Object.ReferenceEquals(Me, other) Then Return True
'            Dim ret As Boolean = True
'            ret = ret AndAlso IsEqual(Me.IdContratoTarifa, other.IdContratoTarifa)
'            ret = ret AndAlso IsEqual(Me.Entorno, other.Entorno)
'            ret = ret AndAlso IsEqual(Me.CodigoContrato, other.CodigoContrato)
'            ret = ret AndAlso IsEqual(Me.IdTarifa, other.IdTarifa)
'            ret = ret AndAlso IsEqual(Me.IdTarifaGrupo, other.IdTarifaGrupo)
'            ret = ret AndAlso IsEqual(Me.IdPerfilFacturacion, other.IdPerfilFacturacion)
'            ret = ret AndAlso IsEqual(Me.FechaDesde, other.FechaDesde)
'            ret = ret AndAlso IsEqual(Me.FechaHasta, other.FechaHasta)
'            ret = ret AndAlso IsEqual(Me.Aviso, other.Aviso)
'            ret = ret AndAlso IsEqual(Me.IdContratoTarifaOld, other.IdContratoTarifaOld)
'            ret = ret AndAlso IsEqual(Me.IsAjusteCAPGas, other.IsAjusteCAPGas)
'            Return ret
'        End Function
'        Public Overrides Function Equals(obj As Object) As Boolean
'            If obj Is Nothing Then Return False
'            Dim DTOObj As ContratoTarifaDTO = TryCast(obj, ContratoTarifaDTO)
'            If DTOObj Is Nothing Then
'                Return False
'            Else
'                Return Equals(DTOObj)
'            End If
'        End Function

'        Public Shared Operator <>(DTO1 As ContratoTarifaDTO, DTO2 As ContratoTarifaDTO) As Boolean
'            If DTO1 Is Nothing OrElse DTO2 Is Nothing Then
'                Return Object.Equals(DTO1, DTO2)
'            End If
'            Return DTO1.Equals(DTO2)
'        End Operator

'        Public Shared Operator =(DTO1 As ContratoTarifaDTO, DTO2 As ContratoTarifaDTO) As Boolean
'            If DTO1 Is Nothing OrElse DTO2 Is Nothing Then
'                Return Not Object.Equals(DTO1, DTO2)
'            End If
'            Return Not DTO1.Equals(DTO2)
'        End Operator


'        Public Overrides Function GetHashCode() As Integer
'            Dim ret As String = String.Empty
'            If Not IsNothing(Me.IdContratoTarifa) Then ret = ret & Me.IdContratoTarifa.GetHashCode().ToString()
'            If Not IsNothing(Me.Entorno) Then ret = ret & Me.Entorno.GetHashCode().ToString()
'            If Not IsNothing(Me.CodigoContrato) Then ret = ret & Me.CodigoContrato.GetHashCode().ToString()
'            If Not IsNothing(Me.IdTarifa) Then ret = ret & Me.IdTarifa.GetHashCode().ToString()
'            If Not IsNothing(Me.IdTarifaGrupo) Then ret = ret & Me.IdTarifaGrupo.GetHashCode().ToString()
'            If Not IsNothing(Me.IdPerfilFacturacion) Then ret = ret & Me.IdPerfilFacturacion.GetHashCode().ToString()
'            If Not IsNothing(Me.FechaDesde) Then ret = ret & Me.FechaDesde.GetHashCode().ToString()
'            If Not IsNothing(Me.FechaHasta) Then ret = ret & Me.FechaHasta.GetHashCode().ToString()
'            If Not IsNothing(Me.Aviso) Then ret = ret & Me.Aviso.GetHashCode().ToString()
'            If Not IsNothing(Me.IdContratoTarifaOld) Then ret = ret & Me.IdContratoTarifaOld.GetHashCode().ToString()
'            If Not IsNothing(Me.IsAjusteCAPGas) Then ret = ret & Me.IsAjusteCAPGas.GetHashCode().ToString()
'            Return ret.GetHashCode()
'        End Function

'        Public Overrides Property IDEntityDTO As Long
'            Get
'                Return IdContratoTarifa
'            End Get
'            Set(value As Long)
'                IdContratoTarifa = value
'            End Set
'        End Property


'        Private _IdContratoTarifa As Long
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IdContratoTarifa As Long
'            Get
'                Return _IdContratoTarifa
'            End Get
'            Set(ByVal value As Long)
'                _IdContratoTarifa = value
'                OnPropertyChanged("IdContratoTarifa")
'            End Set
'        End Property

'        Private _Entorno As String
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property Entorno As String
'            Get
'                Return _Entorno
'            End Get
'            Set(ByVal value As String)
'                _Entorno = value
'                OnPropertyChanged("Entorno")
'            End Set
'        End Property

'        Private _CodigoContrato As Nullable(Of Long)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property CodigoContrato As Nullable(Of Long)
'            Get
'                Return _CodigoContrato
'            End Get
'            Set(ByVal value As Nullable(Of Long))
'                _CodigoContrato = value
'                OnPropertyChanged("CodigoContrato")
'            End Set
'        End Property

'        Private _IdTarifa As Nullable(Of Long)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IdTarifa As Nullable(Of Long)
'            Get
'                Return _IdTarifa
'            End Get
'            Set(ByVal value As Nullable(Of Long))
'                _IdTarifa = value
'                OnPropertyChanged("IdTarifa")
'            End Set
'        End Property

'        Private _IdTarifaGrupo As Nullable(Of Long)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IdTarifaGrupo As Nullable(Of Long)
'            Get
'                Return _IdTarifaGrupo
'            End Get
'            Set(ByVal value As Nullable(Of Long))
'                _IdTarifaGrupo = value
'                OnPropertyChanged("IdTarifaGrupo")
'            End Set
'        End Property

'        Private _IdPerfilFacturacion As Nullable(Of Long)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IdPerfilFacturacion As Nullable(Of Long)
'            Get
'                Return _IdPerfilFacturacion
'            End Get
'            Set(ByVal value As Nullable(Of Long))
'                _IdPerfilFacturacion = value
'                OnPropertyChanged("IdPerfilFacturacion")
'            End Set
'        End Property

'        Private _FechaDesde As Nullable(Of Date)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property FechaDesde As Nullable(Of Date)
'            Get
'                Return _FechaDesde
'            End Get
'            Set(ByVal value As Nullable(Of Date))
'                _FechaDesde = value
'                OnPropertyChanged("FechaDesde")
'            End Set
'        End Property

'        Private _FechaHasta As Nullable(Of Date)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property FechaHasta As Nullable(Of Date)
'            Get
'                Return _FechaHasta
'            End Get
'            Set(ByVal value As Nullable(Of Date))
'                _FechaHasta = value
'                OnPropertyChanged("FechaHasta")
'            End Set
'        End Property

'        Private _Aviso As Nullable(Of Boolean)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property Aviso As Nullable(Of Boolean)
'            Get
'                Return _Aviso
'            End Get
'            Set(ByVal value As Nullable(Of Boolean))
'                _Aviso = value
'                OnPropertyChanged("Aviso")
'            End Set
'        End Property

'        Private _IdContratoTarifaOld As Nullable(Of Long)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IdContratoTarifaOld As Nullable(Of Long)
'            Get
'                Return _IdContratoTarifaOld
'            End Get
'            Set(ByVal value As Nullable(Of Long))
'                _IdContratoTarifaOld = value
'                OnPropertyChanged("IdContratoTarifaOld")
'            End Set
'        End Property

'        Private _IsAjusteCAPGas As Nullable(Of Boolean)
'        ''' <summary>
'        ''' 
'        ''' </summary>
'        <DataMember()>
'        Public Property IsAjusteCAPGas As Nullable(Of Boolean)
'            Get
'                Return _IsAjusteCAPGas
'            End Get
'            Set(ByVal value As Nullable(Of Boolean))
'                _IsAjusteCAPGas = value
'                OnPropertyChanged("IsAjusteCAPGas")
'            End Set
'        End Property

'        ' PerfilFacturacion
'        ' Tarifa
'        ' TarifaGrupo
'        ' ICollection(Of TarifaPerdidaCalculadaContrato)

'    End Class
